---
server:
  port: 8080
  contextPath: /
---
spring:
  profiles: default
datasource:
  sampleapp:
    url: jdbc:mysql://94.73.151.138:3306/stdiosoft
    username: stdiosoft
    password: XYkm50O5
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect

